#!/usr/bin/env bash
WALLPAPER_IMAGE=$(nsxiv -o -t ~/Pictures/wallpaper)

pkill swaybg
swaybg -i $WALLPAPER_IMAGE -m fill > /dev/null 2>&1 & disown

cp -f $WALLPAPER_IMAGE ~/.config/themes/colors-wallpaper.
