#!/usr/bin/env bash
WALLPAPER_IMAGE=$(swayimg -C ~/.config/swayimg/wallpaperrc ~/Pictures/wallpaper)

rm ~/.config/colors-wallpaper/*
cp -t ~/.config/colors-wallpaper/ $WALLPAPER_IMAGE 

killall swaybg
swaybg -i ~/.config/colors-wallpaper/* -m fill & disown
